"""feat: añadir pago_estado a la tabla pago

Revision ID: 00545abfdcab
Revises: bcc8668d32f8
Create Date: 2024-11-05 07:59:02.036424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00545abfdcab'
down_revision: Union[str, None] = 'bcc8668d32f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('pago_estado', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pago', 'pago_estado')
    # ### end Alembic commands ###
