"""add token to usuario table

Revision ID: 06c6638a49c0
Revises: 946357c6f1dc
Create Date: 2025-02-03 15:27:47.397067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06c6638a49c0'
down_revision: Union[str, None] = '946357c6f1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.add_column('usuario', sa.Column('token', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'usuario', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'token')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('next_run_time', mysql.DATETIME(), nullable=True),
    sa.Column('job_state', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
