"""feat: estado_pago y estado en gastoModel

Revision ID: 24c771479fbc
Revises: 0ff0bee58e52
Create Date: 2024-11-05 08:22:01.056252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24c771479fbc'
down_revision: Union[str, None] = '0ff0bee58e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto', sa.Column('gasto_estado', sa.String(length=255), nullable=False))
    op.alter_column('gasto', 'estado',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gasto', 'estado',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('gasto', 'gasto_estado')
    # ### end Alembic commands ###
