"""feat: añadir google_drive_archivo_id

Revision ID: 3632be4b9e7e
Revises: e48e96e984be
Create Date: 2024-11-02 13:24:17.495395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3632be4b9e7e'
down_revision: Union[str, None] = 'e48e96e984be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivo', sa.Column('google_drive_archivo_id', sa.String(length=225), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archivo', 'google_drive_archivo_id')
    # ### end Alembic commands ###
