"""feat: crear tablas

Revision ID: 4cceff3ae27d
Revises: 
Create Date: 2024-10-22 09:34:00.788303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cceff3ae27d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('permiso_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedor',
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=255), nullable=False),
    sa.Column('tipo_proveedor', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=255), nullable=False),
    sa.Column('numero_documento', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('proveedor_id')
    )
    op.create_index(op.f('ix_proveedor_numero_documento'), 'proveedor', ['numero_documento'], unique=True)
    op.create_table('rol',
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tabla_maestra',
    sa.Column('tabla_maestra_id', sa.Uuid(), nullable=False),
    sa.Column('tabla_nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tabla_maestra_id')
    )
    op.create_index(op.f('ix_tabla_maestra_tabla_nombre'), 'tabla_maestra', ['tabla_nombre'], unique=True)
    op.create_index(op.f('ix_tabla_maestra_tipo'), 'tabla_maestra', ['tipo'], unique=False)
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cuenta_bancaria',
    sa.Column('cuenta_bancaria_id', sa.Uuid(), nullable=False),
    sa.Column('banco', sa.String(length=255), nullable=False),
    sa.Column('moneda', sa.String(length=255), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=255), nullable=False),
    sa.Column('cc', sa.String(length=255), nullable=True),
    sa.Column('cci', sa.String(length=255), nullable=True),
    sa.Column('nota', sa.String(length=500), nullable=True),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.proveedor_id'], ),
    sa.PrimaryKeyConstraint('cuenta_bancaria_id')
    )
    op.create_table('gasto',
    sa.Column('gasto_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_gasto', sa.String(length=255), nullable=False),
    sa.Column('tipo_CDP', sa.String(length=255), nullable=False),
    sa.Column('numero_CDP', sa.String(length=255), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=255), nullable=False),
    sa.Column('porcentaje_descuento', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=255), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('naturaleza_gasto', sa.String(length=255), nullable=False),
    sa.Column('centro_costos', sa.String(length=255), nullable=False),
    sa.Column('fecha_pago_tentativa', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_contable', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monto_neto', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.proveedor_id'], ),
    sa.PrimaryKeyConstraint('gasto_id')
    )
    op.create_table('rol_permiso_usuario',
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', 'usuario_id')
    )
    op.create_table('tabla_maestra_detalle',
    sa.Column('tabla_maestra_detalle_id', sa.Uuid(), nullable=False),
    sa.Column('tabla_maestra_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tabla_maestra_id'], ['tabla_maestra.tabla_maestra_id'], ),
    sa.PrimaryKeyConstraint('tabla_maestra_detalle_id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_tabla_maestra_detalle_codigo'), 'tabla_maestra_detalle', ['codigo'], unique=False)
    op.create_index(op.f('ix_tabla_maestra_detalle_valor'), 'tabla_maestra_detalle', ['valor'], unique=False)
    op.create_table('archivo',
    sa.Column('archivo_id', sa.Uuid(), nullable=False),
    sa.Column('webViewLink', sa.String(length=225), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('pathId', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('contentType', sa.String(length=225), nullable=False),
    sa.Column('parent_folder_id', sa.String(length=225), nullable=False),
    sa.Column('gasto_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gasto_id'], ['gasto.gasto_id'], ),
    sa.PrimaryKeyConstraint('archivo_id')
    )
    op.create_table('pago',
    sa.Column('pago_id', sa.Uuid(), nullable=False),
    sa.Column('pago_fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pago_monto', sa.Float(), nullable=False),
    sa.Column('gasto_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gasto_id'], ['gasto.gasto_id'], ),
    sa.PrimaryKeyConstraint('pago_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('archivo')
    op.drop_index(op.f('ix_tabla_maestra_detalle_valor'), table_name='tabla_maestra_detalle')
    op.drop_index(op.f('ix_tabla_maestra_detalle_codigo'), table_name='tabla_maestra_detalle')
    op.drop_table('tabla_maestra_detalle')
    op.drop_table('rol_permiso_usuario')
    op.drop_table('gasto')
    op.drop_table('cuenta_bancaria')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tabla_maestra_tipo'), table_name='tabla_maestra')
    op.drop_index(op.f('ix_tabla_maestra_tabla_nombre'), table_name='tabla_maestra')
    op.drop_table('tabla_maestra')
    op.drop_table('rol')
    op.drop_index(op.f('ix_proveedor_numero_documento'), table_name='proveedor')
    op.drop_table('proveedor')
    op.drop_table('permiso')
    # ### end Alembic commands ###
