"""Agregar codigo, descripcion y es_modulo a PermisoModel

Revision ID: 52db4fa48abb
Revises: e700a720c0fd
Create Date: 2025-05-05 14:31:08.630386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52db4fa48abb'
down_revision: Union[str, None] = 'e700a720c0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permiso', sa.Column('codigo', sa.String(length=50), nullable=False))
    op.add_column('permiso', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.add_column('permiso', sa.Column('es_modulo', sa.Boolean(), nullable=False))
    op.alter_column('permiso', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('nombre', table_name='permiso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nombre', 'permiso', ['nombre'], unique=True)
    op.alter_column('permiso', 'nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('permiso', 'es_modulo')
    op.drop_column('permiso', 'descripcion')
    op.drop_column('permiso', 'codigo')
    # ### end Alembic commands ###
