"""add token to usuario table v2

Revision ID: 776c3477e7c7
Revises: 06c6638a49c0
Create Date: 2025-02-03 16:08:25.014437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776c3477e7c7'
down_revision: Union[str, None] = '06c6638a49c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('token_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'token_verified')
    # ### end Alembic commands ###
