"""feat: pagoModel requiere cuenta_bancaria_id

Revision ID: 8ea081d2eb25
Revises: 6c6de2164cd4
Create Date: 2024-11-05 19:11:29.928641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea081d2eb25'
down_revision: Union[str, None] = '6c6de2164cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('cuenta_bacanria_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pago', 'cuenta_bancaria', ['cuenta_bacanria_id'], ['cuenta_bancaria_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pago', type_='foreignkey')
    op.drop_column('pago', 'cuenta_bacanria_id')
    # ### end Alembic commands ###
