"""feat: modificaciones tablas  auth

Revision ID: a39454f3e8e3
Revises: e8fee7cab5ed
Create Date: 2024-10-23 10:21:26.670291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a39454f3e8e3'
down_revision: Union[str, None] = 'e8fee7cab5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol_permiso',
    sa.Column('rol_permiso_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ),
    sa.PrimaryKeyConstraint('rol_permiso_id')
    )
    op.drop_table('rol_permiso_usuario')
    op.add_column('usuario', sa.Column('rol_permiso_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'rol_permiso', ['rol_permiso_id'], ['rol_permiso_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'rol_permiso_id')
    op.create_table('rol_permiso_usuario',
    sa.Column('rol_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('permiso_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('usuario_id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], name='rol_permiso_usuario_ibfk_1'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], name='rol_permiso_usuario_ibfk_2'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], name='rol_permiso_usuario_ibfk_3'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', 'usuario_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('rol_permiso')
    # ### end Alembic commands ###
