"""feat: fecha_contable ahora puede ser null

Revision ID: bcc8668d32f8
Revises: ed30e1192862
Create Date: 2024-11-04 00:59:11.284530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bcc8668d32f8'
down_revision: Union[str, None] = 'ed30e1192862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gasto', 'fecha_contable',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gasto', 'fecha_contable',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
