"""Cambiar rol_permiso_id a rol_id en usuario

Revision ID: e43fe079dc8f
Revises: fb66585b873d
Create Date: 2025-05-05 18:35:27.921246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e43fe079dc8f'
down_revision: Union[str, None] = 'fb66585b873d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('rol_id', sa.Uuid(), nullable=True))
    op.drop_constraint('usuario_ibfk_1', 'usuario', type_='foreignkey')
    op.create_foreign_key(None, 'usuario', 'rol', ['rol_id'], ['rol_id'])
    op.drop_column('usuario', 'rol_permiso_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('rol_permiso_id', mysql.CHAR(length=32), nullable=True))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.create_foreign_key('usuario_ibfk_1', 'usuario', 'rol_permiso', ['rol_permiso_id'], ['rol_permiso_id'])
    op.drop_column('usuario', 'rol_id')
    # ### end Alembic commands ###
