"""feat: pagoModel cuenta_bancaria_id estaba mal escrito

Revision ID: e4637fc5381e
Revises: 8ea081d2eb25
Create Date: 2024-11-05 22:48:03.540795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4637fc5381e'
down_revision: Union[str, None] = '8ea081d2eb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('cuenta_bancaria_id', sa.Uuid(), nullable=False))
    op.drop_constraint('pago_ibfk_2', 'pago', type_='foreignkey')
    op.create_foreign_key(None, 'pago', 'cuenta_bancaria', ['cuenta_bancaria_id'], ['cuenta_bancaria_id'])
    op.drop_column('pago', 'cuenta_bacanria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('cuenta_bacanria_id', mysql.CHAR(length=32), nullable=False))
    op.drop_constraint(None, 'pago', type_='foreignkey')
    op.create_foreign_key('pago_ibfk_2', 'pago', 'cuenta_bancaria', ['cuenta_bacanria_id'], ['cuenta_bancaria_id'])
    op.drop_column('pago', 'cuenta_bancaria_id')
    # ### end Alembic commands ###
