"""feat: modificar archivo model

Revision ID: e48e96e984be
Revises: a39454f3e8e3
Create Date: 2024-11-02 13:21:37.138918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e48e96e984be'
down_revision: Union[str, None] = 'a39454f3e8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivo', sa.Column('path_id', sa.String(length=255), nullable=False))
    op.add_column('archivo', sa.Column('content_type', sa.String(length=225), nullable=False))
    op.drop_column('archivo', 'pathId')
    op.drop_column('archivo', 'contentType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivo', sa.Column('contentType', mysql.VARCHAR(length=225), nullable=False))
    op.add_column('archivo', sa.Column('pathId', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('archivo', 'content_type')
    op.drop_column('archivo', 'path_id')
    # ### end Alembic commands ###
