"""feat: tabla nombre no unico

Revision ID: e8fee7cab5ed
Revises: 4cceff3ae27d
Create Date: 2024-10-23 01:22:41.878357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fee7cab5ed'
down_revision: Union[str, None] = '4cceff3ae27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tabla_maestra_tabla_nombre', table_name='tabla_maestra')
    op.create_index(op.f('ix_tabla_maestra_tabla_nombre'), 'tabla_maestra', ['tabla_nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tabla_maestra_tabla_nombre'), table_name='tabla_maestra')
    op.create_index('ix_tabla_maestra_tabla_nombre', 'tabla_maestra', ['tabla_nombre'], unique=True)
    # ### end Alembic commands ###
