"""agregar_jerarquia_modulos_permisos

Revision ID: f985791fff3f
Revises: e43fe079dc8f
Create Date: 2025-05-10 19:53:34.290969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f985791fff3f"
down_revision: Union[str, None] = "e43fe079dc8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("permiso", sa.Column("modulo_padre_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None,
        "permiso",
        "permiso",
        ["modulo_padre_id"],
        ["permiso_id"],
    )
    op.drop_column("permiso", "es_modulo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permiso",
        sa.Column(
            "es_modulo",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "permiso", type_="foreignkey")

    op.drop_column("permiso", "modulo_padre_id")
    # ### end Alembic commands ###
