"""Crear PermisoAccionModel

Revision ID: fb66585b873d
Revises: 52db4fa48abb
Create Date: 2025-05-05 14:59:04.948434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb66585b873d'
down_revision: Union[str, None] = '52db4fa48abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso_accion',
    sa.Column('permiso_accion_id', sa.Uuid(), nullable=False),
    sa.Column('permiso_id', sa.Uuid(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.permiso_id'], ),
    sa.PrimaryKeyConstraint('permiso_accion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permiso_accion')
    # ### end Alembic commands ###
