services:
    web:
        image: ${ECR_REPOSITORY_URI}/adelanta-backend-toolbox:latest
        container_name: web
        env_file:
            - ./.env
        ports:
            - "8000:8000"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 650M # Aumentado de 600M a 650M (+50MB)
                reservations:
                    memory: 350M # Aumentado de 300M a 350M (+50MB)
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
        depends_on:
            - redis

    nginx:
        restart: unless-stopped
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        # environment:
        #   - CERTBOT_EMAIL=youremail@gmail.com
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            # - letsencrypt:/etc/letsencrypt
        depends_on:
            - web
        logging:
            driver: "json-file"
            options:
                max-size: "100k"
                max-file: "1"
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: unless-stopped
        command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru
        deploy:
            resources:
                limits:
                    memory: 250M
                reservations:
                    memory: 100M
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"

    celery-worker:
        image: ${ECR_REPOSITORY_URI}/adelanta-backend-toolbox:latest
        container_name: celery_worker
        env_file:
            - ./.env
        command: uv run celery -A config.celery_config worker --loglevel=info --queues=cronjobs,default --concurrency=1 --pool=solo --max-tasks-per-child=1
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 950M # Aumentado de 800M a 950M (+150MB)
                reservations:
                    memory: 500M # Aumentado de 400M a 500M (+100MB)
        volumes:
            - ./templates:/app/templates
        environment:
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis
            - web
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"

    celery-beat:
        image: ${ECR_REPOSITORY_URI}/adelanta-backend-toolbox:latest
        container_name: celery_beat
        env_file:
            - ./.env
        command: uv run celery -A config.celery_config beat --loglevel=info
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 100M
                reservations:
                    memory: 50M
        volumes:
            - ./templates:/app/templates
        environment:
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis
            - celery-worker
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
