services:
    web:
        image: ${ECR_REPOSITORY_URI}/adelanta-backend-toolbox:latest
        container_name: web
        env_file:
            - ./.env
        ports:
            - "8000:8000"
        restart: unless-stopped
        # deploy:
        #     resources:
        #         limits:
        #             memory: 1200M # Aumentado para mejor performance con más workers
        #         reservations:
        #             memory: 600M # Aumentado base memory
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
        depends_on:
            - redis

    nginx:
        restart: unless-stopped
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        # environment:
        #   - CERTBOT_EMAIL=youremail@gmail.com
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            # - letsencrypt:/etc/letsencrypt
        depends_on:
            - web
        logging:
            driver: "json-file"
            options:
                max-size: "100k"
                max-file: "1"
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: unless-stopped
        command: redis-server --maxmemory 400mb --maxmemory-policy allkeys-lru --tcp-keepalive 60 --timeout 300
        deploy:
            resources:
                limits:
                    memory: 500M # Aumentado para manejar más tareas
                reservations:
                    memory: 200M # Aumentado base memory
        logging:
            driver: "json-file"
            options:
                max-file: "2"
                max-size: "150k"

    celery-worker:
        image: ${ECR_REPOSITORY_URI}/adelanta-backend-toolbox:latest
        container_name: celery_worker
        env_file:
            - ./.env
        command: uv run celery -A config.celery_config worker --loglevel=info --queues=cronjobs,default --concurrency=4 --pool=prefork --max-tasks-per-child=5 --prefetch-multiplier=2
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 1200M # Aumentado para manejar más tareas concurrentes
                reservations:
                    memory: 600M # Aumentado base memory
        volumes:
            - ./templates:/app/templates
        environment:
            - REDIS_URL=redis://redis:6379/0
            - CELERY_WORKER_HIJACK_ROOT_LOGGER=False
            - CELERY_WORKER_LOG_FORMAT="[%(asctime)s: %(levelname)s/%(processName)s] %(message)s"
        depends_on:
            - redis
            - web
        logging:
            driver: "json-file"
            options:
                max-file: "3"
                max-size: "200k"

    celery-beat:
        image: ${ECR_REPOSITORY_URI}/adelanta-backend-toolbox:latest
        container_name: celery_beat
        env_file:
            - ./.env
        command: uv run celery -A config.celery_config beat --loglevel=info
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 200M # Aumentado de 100M a 200M
                reservations:
                    memory: 100M # Aumentado de 50M a 100M
        volumes:
            - ./templates:/app/templates
            - ./data/celerybeat:/app/celerybeat # 🆕 Directorio para archivos de beat
        environment:
            - REDIS_URL=redis://redis:6379/0
            - CELERYBEAT_SCHEDULE_FILENAME=/app/celerybeat/celerybeat-schedule # 🆕 Archivo de schedule
        depends_on:
            - redis
            - celery-worker
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
