services:
    web:
        image: mingbling/fastapiwithnginx:latest
        container_name: web
        ports:
            - "8000:8000"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
        depends_on:
            - redis

    nginx:
        restart: unless-stopped
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        # environment:
        #   - CERTBOT_EMAIL=youremail@gmail.com
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            # - letsencrypt:/etc/letsencrypt
        depends_on:
            - web
        logging:
            driver: "json-file"
            options:
                max-size: "100k"
                max-file: "1"
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"

    worker:
        image: mingbling/fastapiwithnginx:latest
        container_name: rq_worker
        command: rq worker --name worker@%h --with-scheduler emails
        restart: unless-stopped
        # env_file:
        # - ./.env  # Cargar todas las variables del archivo .env
        volumes:
        - ./templates:/app/templates
        environment:
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis
            - web
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "100k"
