"""feat: crear tabla referidos

Revision ID: 0bc6cfa461e7
Revises: 4fc9971f2d8a
Create Date: 2025-02-18 10:04:10.368456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc6cfa461e7'
down_revision: Union[str, None] = '4fc9971f2d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
