"""crear KPIModel

Revision ID: 0d5e35d11f2d
Revises: 3e889f3e5f5e
Create Date: 2025-05-20 19:03:44.410646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5e35d11f2d'
down_revision: Union[str, None] = '3e889f3e5f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CodigoLiquidacion', sa.String(length=255), nullable=False),
    sa.Column('CodigoSolicitud', sa.String(length=255), nullable=True),
    sa.Column('RUCCliente', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialCliente', sa.String(length=255), nullable=False),
    sa.Column('RUCPagador', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialPagador', sa.String(length=255), nullable=False),
    sa.Column('Moneda', sa.String(length=255), nullable=False),
    sa.Column('DeudaAnterior', sa.Float(), nullable=False),
    sa.Column('ObservacionLiquidacion', sa.String(length=255), nullable=True),
    sa.Column('ObservacionSolicitud', sa.String(length=255), nullable=True),
    sa.Column('FlagPagoInteresConfirming', sa.String(length=255), nullable=True),
    sa.Column('TipoOperacion', sa.String(length=255), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.Column('NroDocumento', sa.String(length=255), nullable=False),
    sa.Column('TasaNominalMensualPorc', sa.Float(), nullable=False),
    sa.Column('FinanciamientoPorc', sa.Float(), nullable=False),
    sa.Column('FechaConfirmado', sa.DateTime(), nullable=True),
    sa.Column('FechaOperacion', sa.DateTime(), nullable=False),
    sa.Column('DiasEfectivo', sa.Integer(), nullable=False),
    sa.Column('NetoConfirmado', sa.Float(), nullable=False),
    sa.Column('FondoResguardo', sa.Float(), nullable=False),
    sa.Column('MontoNegociado', sa.Float(), nullable=False),
    sa.Column('MontoNegociadoSoles', sa.Float(), nullable=True),
    sa.Column('MontoComisionEstructuracion', sa.Float(), nullable=False),
    sa.Column('ComisionEstructuracionIGV', sa.Float(), nullable=False),
    sa.Column('ComisionEstructuracionConIGV', sa.Float(), nullable=False),
    sa.Column('MontoCobrar', sa.Float(), nullable=False),
    sa.Column('Interes', sa.Float(), nullable=False),
    sa.Column('InteresConIGV', sa.Float(), nullable=False),
    sa.Column('GastosContrato', sa.Float(), nullable=False),
    sa.Column('GastoVigenciaPoder', sa.Float(), nullable=False),
    sa.Column('ServicioCobranza', sa.Float(), nullable=False),
    sa.Column('ServicioCustodia', sa.Float(), nullable=False),
    sa.Column('GastosDiversosIGV', sa.Float(), nullable=False),
    sa.Column('GastosDiversosConIGV', sa.Float(), nullable=False),
    sa.Column('MontoTotalFacturado', sa.Float(), nullable=False),
    sa.Column('MontoDesembolso', sa.Float(), nullable=False),
    sa.Column('FacturasGeneradas', sa.String(length=255), nullable=False),
    sa.Column('Ejecutivo', sa.String(length=255), nullable=False),
    sa.Column('Referencia', sa.String(length=255), nullable=True),
    sa.Column('FechaPago', sa.DateTime(), nullable=True),
    sa.Column('MontoPago', sa.Float(), nullable=False),
    sa.Column('MontoPagoSoles', sa.Float(), nullable=False),
    sa.Column('ExcesoPago', sa.Float(), nullable=False),
    sa.Column('FechaDesembolso', sa.DateTime(), nullable=True),
    sa.Column('MontoDevolucion', sa.Float(), nullable=False),
    sa.Column('EstadoDevolucion', sa.String(length=255), nullable=True),
    sa.Column('Anticipo', sa.String(length=255), nullable=True),
    sa.Column('TramoAnticipo', sa.String(length=255), nullable=True),
    sa.Column('Mes', sa.String(length=255), nullable=False),
    sa.Column('Año', sa.String(length=255), nullable=False),
    sa.Column('MesAño', sa.String(length=255), nullable=False),
    sa.Column('TipoCambioFecha', sa.DateTime(), nullable=True),
    sa.Column('TipoCambioCompra', sa.Float(), nullable=True),
    sa.Column('TipoCambioVenta', sa.Float(), nullable=True),
    sa.Column('ColocacionSoles', sa.Float(), nullable=False),
    sa.Column('MontoDesembolsoSoles', sa.Float(), nullable=False),
    sa.Column('Ingresos', sa.Float(), nullable=False),
    sa.Column('IngresosSoles', sa.Float(), nullable=False),
    sa.Column('MesSemana', sa.String(length=255), nullable=False),
    sa.Column('CostosFondo', sa.Float(), nullable=False),
    sa.Column('TotalIngresos', sa.Float(), nullable=False),
    sa.Column('CostosFondoSoles', sa.Float(), nullable=False),
    sa.Column('TotalIngresosSoles', sa.Float(), nullable=False),
    sa.Column('Utilidad', sa.Float(), nullable=False),
    sa.Column('Sector', sa.String(length=255), nullable=True),
    sa.Column('GrupoEco', sa.String(length=255), nullable=True),
    sa.Column('FueraSistema', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi')
    # ### end Alembic commands ###
