"""feat: crear tabla referidos

Revision ID: 134989d911c0
Revises: 0bc6cfa461e7
Create Date: 2025-02-18 10:13:58.692787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134989d911c0'
down_revision: Union[str, None] = '0bc6cfa461e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
