"""feat: agregar tabla actualizacion reportes, formato Lima/Peru v2

Revision ID: 24603ac843dc
Revises: c4cb328a43ed
Create Date: 2025-04-14 19:20:36.117282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24603ac843dc'
down_revision: Union[str, None] = 'c4cb328a43ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
