"""eliminar KPIModel

Revision ID: 3e889f3e5f5e
Revises: 2ec2c63e7781
Create Date: 2025-05-20 18:56:15.172371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e889f3e5f5e'
down_revision: Union[str, None] = '2ec2c63e7781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CodigoLiquidacion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CodigoSolicitud', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RUCCliente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RazonSocialCliente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RUCPagador', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RazonSocialPagador', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Moneda', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('DeudaAnterior', mysql.FLOAT(), nullable=False),
    sa.Column('ObservacionLiquidacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ObservacionSolicitud', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FlagPagoInteresConfirming', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TipoOperacion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Estado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('NroDocumento', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('TasaNominalMensualPorc', mysql.FLOAT(), nullable=False),
    sa.Column('FinanciamientoPorc', mysql.FLOAT(), nullable=False),
    sa.Column('FechaConfirmado', mysql.DATETIME(), nullable=True),
    sa.Column('FechaOperacion', mysql.DATETIME(), nullable=False),
    sa.Column('DiasEfectivo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NetoConfirmado', mysql.FLOAT(), nullable=False),
    sa.Column('FondoResguardo', mysql.FLOAT(), nullable=False),
    sa.Column('MontoComisionEstructuracion', mysql.FLOAT(), nullable=False),
    sa.Column('ComisionEstructuracionIGV', mysql.FLOAT(), nullable=False),
    sa.Column('ComisionEstructuracionConIGV', mysql.FLOAT(), nullable=False),
    sa.Column('MontoCobrar', mysql.FLOAT(), nullable=False),
    sa.Column('Interes', mysql.FLOAT(), nullable=False),
    sa.Column('InteresConIGV', mysql.FLOAT(), nullable=False),
    sa.Column('GastosContrato', mysql.FLOAT(), nullable=False),
    sa.Column('GastoVigenciaPoder', mysql.FLOAT(), nullable=False),
    sa.Column('ServicioCobranza', mysql.FLOAT(), nullable=False),
    sa.Column('ServicioCustodia', mysql.FLOAT(), nullable=False),
    sa.Column('GastosDiversosIGV', mysql.FLOAT(), nullable=False),
    sa.Column('GastosDiversosConIGV', mysql.FLOAT(), nullable=False),
    sa.Column('MontoTotalFacturado', mysql.FLOAT(), nullable=False),
    sa.Column('MontoDesembolso', mysql.FLOAT(), nullable=False),
    sa.Column('FacturasGeneradas', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Ejecutivo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MontoPago', mysql.FLOAT(), nullable=False),
    sa.Column('MontoPagoSoles', mysql.FLOAT(), nullable=False),
    sa.Column('ExcesoPago', mysql.FLOAT(), nullable=False),
    sa.Column('FechaDesembolso', mysql.DATETIME(), nullable=True),
    sa.Column('MontoDevolucion', mysql.FLOAT(), nullable=False),
    sa.Column('EstadoDevolucion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Anticipo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TramoAnticipo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Mes', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Año', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MesAño', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ColocacionSoles', mysql.FLOAT(), nullable=False),
    sa.Column('MontoDesembolsoSoles', mysql.FLOAT(), nullable=False),
    sa.Column('Ingresos', mysql.FLOAT(), nullable=False),
    sa.Column('IngresosSoles', mysql.FLOAT(), nullable=False),
    sa.Column('MesSemana', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CostosFondo', mysql.FLOAT(), nullable=False),
    sa.Column('TotalIngresos', mysql.FLOAT(), nullable=False),
    sa.Column('CostosFondoSoles', mysql.FLOAT(), nullable=False),
    sa.Column('TotalIngresosSoles', mysql.FLOAT(), nullable=False),
    sa.Column('Utilidad', mysql.FLOAT(), nullable=False),
    sa.Column('Sector', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GrupoEco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FueraSistema', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('MontoNegociado', mysql.FLOAT(), nullable=False),
    sa.Column('MontoNegociadoSoles', mysql.FLOAT(), nullable=True),
    sa.Column('FechaPago', mysql.DATETIME(), nullable=True),
    sa.Column('TipoCambioFecha', mysql.DATETIME(), nullable=True),
    sa.Column('TipoCambioCompra', mysql.FLOAT(), nullable=True),
    sa.Column('TipoCambioVenta', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
