"""fix: id entero y no uuid4

Revision ID: 4700bb28c033
Revises: 6efd86bbdba9
Create Date: 2025-07-21 20:14:20.051695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4700bb28c033'
down_revision: Union[str, None] = '6efd86bbdba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi_acumulado', 'id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi_acumulado', 'id',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
