"""feat: agregar tabla actualizacion reportes, formato Lima/Peru v3

Revision ID: 4b5345d8b369
Revises: 24603ac843dc
Create Date: 2025-04-14 19:21:49.505446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b5345d8b369'
down_revision: Union[str, None] = '24603ac843dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actualizacion_reportes', 'ultima_actualizacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualizacion_reportes', sa.Column('ultima_actualizacion', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
