"""feat: añadir MontoNegociadoSoles

Revision ID: 4fc9971f2d8a
Revises: e9f39f240b8e
Create Date: 2024-10-16 08:33:07.165147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc9971f2d8a'
down_revision: Union[str, None] = 'e9f39f240b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('MontoNegociadoSoles', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'MontoNegociadoSoles')
    # ### end Alembic commands ###
