"""feat: agregar tabla actualización

Revision ID: 599b27df5429
Revises: 762767fe468b
Create Date: 2025-04-15 08:57:03.786857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599b27df5429'
down_revision: Union[str, None] = '762767fe468b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actualizacion_reportes',
    sa.Column('actualizacion_reporte_id', sa.Uuid(), nullable=False),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('actualizacion_reporte_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actualizacion_reportes')
    # ### end Alembic commands ###
