"""fix: quitar y reemplazar por columnas de tipoCambio correctas

Revision ID: 6efd86bbdba9
Revises: 7aaec57243b7
Create Date: 2025-07-21 20:12:18.562737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6efd86bbdba9'
down_revision: Union[str, None] = '7aaec57243b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_acumulado', sa.Column('TipoCambioFecha', sa.DateTime(), nullable=True))
    op.add_column('kpi_acumulado', sa.Column('TipoCambioCompra', sa.Float(), nullable=True))
    op.add_column('kpi_acumulado', sa.Column('TipoCambioVenta', sa.Float(), nullable=True))
    op.drop_column('kpi_acumulado', 'tcCompra')
    op.drop_column('kpi_acumulado', 'tcFecha')
    op.drop_column('kpi_acumulado', 'tcVenta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_acumulado', sa.Column('tcVenta', mysql.FLOAT(), nullable=True))
    op.add_column('kpi_acumulado', sa.Column('tcFecha', mysql.DATETIME(), nullable=True))
    op.add_column('kpi_acumulado', sa.Column('tcCompra', mysql.FLOAT(), nullable=True))
    op.drop_column('kpi_acumulado', 'TipoCambioVenta')
    op.drop_column('kpi_acumulado', 'TipoCambioCompra')
    op.drop_column('kpi_acumulado', 'TipoCambioFecha')
    # ### end Alembic commands ###
