"""feat: crear tablas

Revision ID: 7371459965cf
Revises: 4d16ebefbf3b
Create Date: 2024-09-24 08:30:04.258488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7371459965cf'
down_revision: Union[str, None] = '4d16ebefbf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CodigoLiquidacion', sa.String(length=255), nullable=False),
    sa.Column('CodigoSolicitud', sa.String(length=255), nullable=True),
    sa.Column('RUCCliente', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialCliente', sa.String(length=255), nullable=False),
    sa.Column('RUCPagador', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialPagador', sa.String(length=255), nullable=False),
    sa.Column('Moneda', sa.String(length=255), nullable=False),
    sa.Column('DeudaAnterior', sa.Float(), nullable=False),
    sa.Column('ObservacionLiquidacion', sa.String(length=255), nullable=True),
    sa.Column('ObservacionSolicitud', sa.String(length=255), nullable=True),
    sa.Column('FlagPagoInteresConfirming', sa.String(length=255), nullable=True),
    sa.Column('TipoOperacion', sa.String(length=255), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.Column('NroDocumento', sa.String(length=255), nullable=False),
    sa.Column('TasaNominalMensualPorc', sa.Float(), nullable=False),
    sa.Column('FinanciamientoPorc', sa.Float(), nullable=False),
    sa.Column('FechaConfirmado', sa.DateTime(), nullable=False),
    sa.Column('FechaOperacion', sa.DateTime(), nullable=False),
    sa.Column('DiasEfectivo', sa.Integer(), nullable=False),
    sa.Column('NetoConfirmado', sa.Float(), nullable=False),
    sa.Column('FondoResguardo', sa.Float(), nullable=False),
    sa.Column('MontoComisionEstructuracion', sa.Float(), nullable=False),
    sa.Column('ComisionEstructuracionIGV', sa.Float(), nullable=False),
    sa.Column('ComisionEstructuracionConIGV', sa.Float(), nullable=False),
    sa.Column('MontoCobrar', sa.Float(), nullable=False),
    sa.Column('Interes', sa.Float(), nullable=False),
    sa.Column('InteresConIGV', sa.Float(), nullable=False),
    sa.Column('GastosContrato', sa.Float(), nullable=False),
    sa.Column('GastoVigenciaPoder', sa.Float(), nullable=False),
    sa.Column('ServicioCobranza', sa.Float(), nullable=False),
    sa.Column('ServicioCustodia', sa.Float(), nullable=False),
    sa.Column('GastosDiversosIGV', sa.Float(), nullable=False),
    sa.Column('GastosDiversosConIGV', sa.Float(), nullable=False),
    sa.Column('MontoTotalFacturado', sa.Float(), nullable=False),
    sa.Column('MontoDesembolso', sa.Float(), nullable=False),
    sa.Column('FacturasGeneradas', sa.String(length=255), nullable=False),
    sa.Column('Ejecutivo', sa.String(length=255), nullable=False),
    sa.Column('MontoPago', sa.Float(), nullable=False),
    sa.Column('MontoPagoSoles', sa.Float(), nullable=False),
    sa.Column('ExcesoPago', sa.Float(), nullable=False),
    sa.Column('FechaDesembolso', sa.DateTime(), nullable=True),
    sa.Column('MontoDevolucion', sa.Float(), nullable=False),
    sa.Column('EstadoDevolucion', sa.String(length=255), nullable=True),
    sa.Column('Anticipo', sa.String(length=255), nullable=True),
    sa.Column('TramoAnticipo', sa.String(length=255), nullable=True),
    sa.Column('Mes', sa.String(length=255), nullable=False),
    sa.Column('Año', sa.String(length=255), nullable=False),
    sa.Column('MesAño', sa.String(length=255), nullable=False),
    sa.Column('tcFecha', sa.DateTime(), nullable=True),
    sa.Column('tcCompra', sa.Float(), nullable=True),
    sa.Column('tcVenta', sa.Float(), nullable=True),
    sa.Column('ColocacionSoles', sa.Float(), nullable=False),
    sa.Column('MontoDesembolsoSoles', sa.Float(), nullable=False),
    sa.Column('Ingresos', sa.Float(), nullable=False),
    sa.Column('IngresosSoles', sa.Float(), nullable=False),
    sa.Column('MesSemana', sa.String(length=255), nullable=False),
    sa.Column('CostosFondo', sa.Float(), nullable=False),
    sa.Column('TotalIngresos', sa.Float(), nullable=False),
    sa.Column('CostosFondoSoles', sa.Float(), nullable=False),
    sa.Column('TotalIngresosSoles', sa.Float(), nullable=False),
    sa.Column('Utilidad', sa.Float(), nullable=False),
    sa.Column('Sector', sa.String(length=255), nullable=True),
    sa.Column('GrupoEco', sa.String(length=255), nullable=True),
    sa.Column('FueraSistema', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('colocaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colocaciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CodigoLiquidacion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CodigoSolicitud', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RUCCliente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RazonSocialCliente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RUCPagador', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('RazonSocialPagador', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Moneda', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('DeudaAnterior', mysql.FLOAT(), nullable=False),
    sa.Column('ObservacionLiquidacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ObservacionSolicitud', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FlagPagoInteresConfirming', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TipoOperacion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Estado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('NroDocumento', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('TasaNominalMensualPorc', mysql.FLOAT(), nullable=False),
    sa.Column('FinanciamientoPorc', mysql.FLOAT(), nullable=False),
    sa.Column('FechaConfirmado', mysql.DATETIME(), nullable=False),
    sa.Column('FechaOperacion', mysql.DATETIME(), nullable=False),
    sa.Column('DiasEfectivo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NetoConfirmado', mysql.FLOAT(), nullable=False),
    sa.Column('FondoResguardo', mysql.FLOAT(), nullable=False),
    sa.Column('MontoComisionEstructuracion', mysql.FLOAT(), nullable=False),
    sa.Column('ComisionEstructuracionIGV', mysql.FLOAT(), nullable=False),
    sa.Column('ComisionEstructuracionConIGV', mysql.FLOAT(), nullable=False),
    sa.Column('MontoCobrar', mysql.FLOAT(), nullable=False),
    sa.Column('Interes', mysql.FLOAT(), nullable=False),
    sa.Column('InteresConIGV', mysql.FLOAT(), nullable=False),
    sa.Column('GastosContrato', mysql.FLOAT(), nullable=False),
    sa.Column('GastoVigenciaPoder', mysql.FLOAT(), nullable=False),
    sa.Column('ServicioCobranza', mysql.FLOAT(), nullable=False),
    sa.Column('ServicioCustodia', mysql.FLOAT(), nullable=False),
    sa.Column('GastosDiversosIGV', mysql.FLOAT(), nullable=False),
    sa.Column('GastosDiversosConIGV', mysql.FLOAT(), nullable=False),
    sa.Column('MontoTotalFacturado', mysql.FLOAT(), nullable=False),
    sa.Column('MontoDesembolso', mysql.FLOAT(), nullable=False),
    sa.Column('FacturasGeneradas', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Ejecutivo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MontoPago', mysql.FLOAT(), nullable=False),
    sa.Column('MontoPagoSoles', mysql.FLOAT(), nullable=False),
    sa.Column('ExcesoPago', mysql.FLOAT(), nullable=False),
    sa.Column('FechaDesembolso', mysql.DATETIME(), nullable=True),
    sa.Column('MontoDevolucion', mysql.FLOAT(), nullable=False),
    sa.Column('EstadoDevolucion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Anticipo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TramoAnticipo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Mes', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Año', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MesAño', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tcFecha', mysql.DATETIME(), nullable=True),
    sa.Column('tcCompra', mysql.FLOAT(), nullable=True),
    sa.Column('tcVenta', mysql.FLOAT(), nullable=True),
    sa.Column('ColocacionSoles', mysql.FLOAT(), nullable=False),
    sa.Column('MontoDesembolsoSoles', mysql.FLOAT(), nullable=False),
    sa.Column('Ingresos', mysql.FLOAT(), nullable=False),
    sa.Column('IngresosSoles', mysql.FLOAT(), nullable=False),
    sa.Column('MesSemana', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('CostosFondo', mysql.FLOAT(), nullable=False),
    sa.Column('TotalIngresos', mysql.FLOAT(), nullable=False),
    sa.Column('CostosFondoSoles', mysql.FLOAT(), nullable=False),
    sa.Column('TotalIngresosSoles', mysql.FLOAT(), nullable=False),
    sa.Column('Utilidad', mysql.FLOAT(), nullable=False),
    sa.Column('Sector', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GrupoEco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FueraSistema', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('kpi')
    # ### end Alembic commands ###
