"""feat: formato Lima/Peru v4- agregar

Revision ID: 762767fe468b
Revises: fb48631a8b4b
Create Date: 2025-04-14 19:44:38.609258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762767fe468b'
down_revision: Union[str, None] = 'fb48631a8b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualizacion_reportes', sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actualizacion_reportes', 'ultima_actualizacion')
    # ### end Alembic commands ###
