"""feat: añadir tabla KPIAcumulado

Revision ID: 8b12633c419a
Revises: 9f1523850ae0
Create Date: 2024-10-07 14:06:51.577560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b12633c419a'
down_revision: Union[str, None] = '9f1523850ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
