"""feat: agregar tabla actualizacion reportes

Revision ID: 9047d50da03c
Revises: d4b6d8789b26
Create Date: 2025-04-14 19:02:54.361770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9047d50da03c'
down_revision: Union[str, None] = 'd4b6d8789b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
