"""feat: agregar columnas MontoNegociado y MontoNegociadoSoles a KPIAcumuladoModel

Revision ID: 94a2198ecc55
Revises: 99d0232d9e1a
Create Date: 2025-08-07 11:16:28.145878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a2198ecc55'
down_revision: Union[str, None] = '99d0232d9e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_acumulado', sa.Column('MontoNegociado', sa.Float(), nullable=False))
    op.add_column('kpi_acumulado', sa.Column('MontoNegociadoSoles', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_acumulado', 'MontoNegociadoSoles')
    op.drop_column('kpi_acumulado', 'MontoNegociado')
    # ### end Alembic commands ###
