"""feat: agregar campos KPI Acumulado campos pendientes

Revision ID: 99d0232d9e1a
Revises: c6237109ab6b
Create Date: 2025-08-06 02:07:06.332092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d0232d9e1a'
down_revision: Union[str, None] = 'c6237109ab6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_acumulado', sa.Column('FechaPagoCreacion', sa.DateTime(), nullable=True))
    op.add_column('kpi_acumulado', sa.Column('FechaPagoModificacion', sa.DateTime(), nullable=True))
    op.add_column('kpi_acumulado', sa.Column('TipoOperacionDetalle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_acumulado', 'TipoOperacionDetalle')
    op.drop_column('kpi_acumulado', 'FechaPagoModificacion')
    op.drop_column('kpi_acumulado', 'FechaPagoCreacion')
    # ### end Alembic commands ###
