"""feat: añadir tabla KPIAcumulado v2

Revision ID: 9efafb6f4cc9
Revises: 8b12633c419a
Create Date: 2024-10-07 14:07:38.792875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efafb6f4cc9'
down_revision: Union[str, None] = '8b12633c419a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_acumulado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('CodigoLiquidacion', sa.String(length=255), nullable=False),
    sa.Column('CodigoSolicitud', sa.String(length=255), nullable=True),
    sa.Column('RUCCliente', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialCliente', sa.String(length=255), nullable=False),
    sa.Column('RUCPagador', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialPagador', sa.String(length=255), nullable=False),
    sa.Column('Moneda', sa.String(length=255), nullable=False),
    sa.Column('DeudaAnterior', sa.Float(), nullable=False),
    sa.Column('ObservacionLiquidacion', sa.String(length=255), nullable=True),
    sa.Column('ObservacionSolicitud', sa.String(length=255), nullable=True),
    sa.Column('FlagPagoInteresConfirming', sa.String(length=255), nullable=True),
    sa.Column('FechaInteresConfirming', sa.DateTime(), nullable=True),
    sa.Column('TipoOperacion', sa.String(length=255), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.Column('NroDocumento', sa.String(length=255), nullable=False),
    sa.Column('TasaNominalMensualPorc', sa.Float(), nullable=False),
    sa.Column('FinanciamientoPorc', sa.Float(), nullable=False),
    sa.Column('FechaConfirmado', sa.DateTime(), nullable=False),
    sa.Column('FechaOperacion', sa.DateTime(), nullable=False),
    sa.Column('DiasEfectivo', sa.Integer(), nullable=False),
    sa.Column('NetoConfirmado', sa.Float(), nullable=False),
    sa.Column('FondoResguardo', sa.Float(), nullable=False),
    sa.Column('MontoComisionEstructuracion', sa.Float(), nullable=False),
    sa.Column('ComisionEstructuracionIGV', sa.Float(), nullable=False),
    sa.Column('ComisionEstructuracionConIGV', sa.Float(), nullable=False),
    sa.Column('MontoCobrar', sa.Float(), nullable=False),
    sa.Column('Interes', sa.Float(), nullable=False),
    sa.Column('InteresConIGV', sa.Float(), nullable=False),
    sa.Column('GastosContrato', sa.Float(), nullable=False),
    sa.Column('GastoVigenciaPoder', sa.Float(), nullable=False),
    sa.Column('ServicioCobranza', sa.Float(), nullable=False),
    sa.Column('ServicioCustodia', sa.Float(), nullable=False),
    sa.Column('GastosDiversosIGV', sa.Float(), nullable=False),
    sa.Column('GastosDiversosConIGV', sa.Float(), nullable=False),
    sa.Column('MontoTotalFacturado', sa.Float(), nullable=False),
    sa.Column('MontoDesembolso', sa.Float(), nullable=False),
    sa.Column('FacturasGeneradas', sa.String(length=255), nullable=False),
    sa.Column('Ejecutivo', sa.String(length=255), nullable=False),
    sa.Column('FechaPago', sa.DateTime(), nullable=True),
    sa.Column('DiasMora', sa.Integer(), nullable=True),
    sa.Column('MontoCobrarPago', sa.Float(), nullable=True),
    sa.Column('MontoPago', sa.Float(), nullable=False),
    sa.Column('FacturasMoraGeneradas', sa.String(length=255), nullable=True),
    sa.Column('InteresPago', sa.Float(), nullable=True),
    sa.Column('GastosPago', sa.Float(), nullable=True),
    sa.Column('TipoPago', sa.String(length=255), nullable=True),
    sa.Column('SaldoDeuda', sa.Float(), nullable=True),
    sa.Column('ExcesoPago', sa.Float(), nullable=False),
    sa.Column('ObservacionPago', sa.String(length=255), nullable=True),
    sa.Column('FechaDesembolso', sa.DateTime(), nullable=True),
    sa.Column('MontoDevolucion', sa.Float(), nullable=False),
    sa.Column('DescuentoDevolucion', sa.Float(), nullable=True),
    sa.Column('EstadoDevolucion', sa.String(length=255), nullable=True),
    sa.Column('ObservacionDevolucion', sa.String(length=255), nullable=True),
    sa.Column('Anticipo', sa.String(length=255), nullable=True),
    sa.Column('TramoAnticipo', sa.String(length=255), nullable=True),
    sa.Column('FueraSistema', sa.String(length=255), nullable=True),
    sa.Column('GastosDiversosSinIGV', sa.Float(), nullable=True),
    sa.Column('Mes', sa.String(length=255), nullable=False),
    sa.Column('Año', sa.String(length=255), nullable=False),
    sa.Column('MesAño', sa.String(length=255), nullable=False),
    sa.Column('Sector', sa.String(length=255), nullable=True),
    sa.Column('GrupoEco', sa.String(length=255), nullable=True),
    sa.Column('Referencia', sa.String(length=255), nullable=True),
    sa.Column('tcFecha', sa.DateTime(), nullable=True),
    sa.Column('tcCompra', sa.Float(), nullable=True),
    sa.Column('tcVenta', sa.Float(), nullable=True),
    sa.Column('ColocacionSoles', sa.Float(), nullable=False),
    sa.Column('MontoDesembolsoSoles', sa.Float(), nullable=False),
    sa.Column('Ingresos', sa.Float(), nullable=False),
    sa.Column('IngresosSoles', sa.Float(), nullable=False),
    sa.Column('MesSemana', sa.String(length=255), nullable=False),
    sa.Column('CostosFondo', sa.Float(), nullable=False),
    sa.Column('TotalIngresos', sa.Float(), nullable=False),
    sa.Column('CostosFondoSoles', sa.Float(), nullable=False),
    sa.Column('TotalIngresosSoles', sa.Float(), nullable=False),
    sa.Column('MontoPagoSoles', sa.Float(), nullable=False),
    sa.Column('Utilidad', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_acumulado')
    # ### end Alembic commands ###
