"""feat: modificar tablas

Revision ID: 9f1523850ae0
Revises: 5fffd0154a82
Create Date: 2024-09-24 21:17:55.060129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f1523850ae0'
down_revision: Union[str, None] = '5fffd0154a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saldos', sa.Column('FechaOperacion', sa.DateTime(), nullable=False))
    op.drop_column('saldos', 'Fecha')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saldos', sa.Column('Fecha', mysql.DATETIME(), nullable=False))
    op.drop_column('saldos', 'FechaOperacion')
    # ### end Alembic commands ###
