"""feat: formato Lima/Peru v4

Revision ID: a40f4202cd50
Revises: 4b5345d8b369
Create Date: 2025-04-14 19:23:18.604092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a40f4202cd50'
down_revision: Union[str, None] = '4b5345d8b369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualizacion_reportes', sa.Column('actualizacion_reporte_id', sa.Uuid(), nullable=False))
    op.add_column('actualizacion_reportes', sa.Column('ultima_actualizacion', sa.DateTime(timezone='America/Lima'), nullable=False))
    op.drop_column('actualizacion_reportes', 'acutalizacion_reporte_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualizacion_reportes', sa.Column('acutalizacion_reporte_id', mysql.CHAR(length=32), nullable=False))
    op.drop_column('actualizacion_reportes', 'ultima_actualizacion')
    op.drop_column('actualizacion_reportes', 'actualizacion_reporte_id')
    # ### end Alembic commands ###
