"""feat: agregar tabla actualizacion reportes v2

Revision ID: a611f8af9aa1
Revises: 9047d50da03c
Create Date: 2025-04-14 19:04:08.286915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a611f8af9aa1'
down_revision: Union[str, None] = '9047d50da03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actualizacion_reportes',
    sa.Column('acutalizacion_reporte_id', sa.Uuid(), nullable=False),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('acutalizacion_reporte_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actualizacion_reportes')
    # ### end Alembic commands ###
