"""feat: agregar campos KPI restantes a CXCAcumuladoDIM

Revision ID: bbcac535488f
Revises: 4700bb28c033
Create Date: 2025-07-24 21:30:22.591979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcac535488f'
down_revision: Union[str, None] = '4700bb28c033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CXCAcumuladoDim', sa.Column('Mes', sa.String(length=10), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('Año', sa.String(length=4), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('MesAño', sa.String(length=20), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('MesSemana', sa.String(length=20), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('TipoCambioFecha', sa.Date(), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('TipoCambioCompra', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('TipoCambioVenta', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('ColocacionSoles', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('MontoDesembolsoSoles', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('Ingresos', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('IngresosSoles', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('CostosFondo', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('TotalIngresos', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('CostosFondoSoles', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('TotalIngresosSoles', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('Utilidad', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('FueraSistema', sa.String(length=10), nullable=True))
    op.add_column('CXCAcumuladoDim', sa.Column('Referencia', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CXCAcumuladoDim', 'Referencia')
    op.drop_column('CXCAcumuladoDim', 'FueraSistema')
    op.drop_column('CXCAcumuladoDim', 'Utilidad')
    op.drop_column('CXCAcumuladoDim', 'TotalIngresosSoles')
    op.drop_column('CXCAcumuladoDim', 'CostosFondoSoles')
    op.drop_column('CXCAcumuladoDim', 'TotalIngresos')
    op.drop_column('CXCAcumuladoDim', 'CostosFondo')
    op.drop_column('CXCAcumuladoDim', 'IngresosSoles')
    op.drop_column('CXCAcumuladoDim', 'Ingresos')
    op.drop_column('CXCAcumuladoDim', 'MontoDesembolsoSoles')
    op.drop_column('CXCAcumuladoDim', 'ColocacionSoles')
    op.drop_column('CXCAcumuladoDim', 'TipoCambioVenta')
    op.drop_column('CXCAcumuladoDim', 'TipoCambioCompra')
    op.drop_column('CXCAcumuladoDim', 'TipoCambioFecha')
    op.drop_column('CXCAcumuladoDim', 'MesSemana')
    op.drop_column('CXCAcumuladoDim', 'MesAño')
    op.drop_column('CXCAcumuladoDim', 'Año')
    op.drop_column('CXCAcumuladoDim', 'Mes')
    # ### end Alembic commands ###
