"""feat: agregar tabla actualizacion reportes, formato Lima/Peru 

Revision ID: c4cb328a43ed
Revises: a611f8af9aa1
Create Date: 2025-04-14 19:16:06.040140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cb328a43ed'
down_revision: Union[str, None] = 'a611f8af9aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
