"""feat: agregar campos KPI restantes a CXCAcumuladoDIM

Revision ID: c6237109ab6b
Revises: bbcac535488f
Create Date: 2025-07-24 21:42:53.847058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6237109ab6b'
down_revision: Union[str, None] = 'bbcac535488f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
