"""feat: crear tabla referidos v2

Revision ID: d22f0e1f7a08
Revises: 134989d911c0
Create Date: 2025-02-18 10:15:23.848990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22f0e1f7a08'
down_revision: Union[str, None] = '134989d911c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Referencia', sa.String(length=255), nullable=True),
    sa.Column('Moneda', sa.String(length=255), nullable=False),
    sa.Column('CodigoLiquidacion', sa.String(length=255), nullable=False),
    sa.Column('NroDocumento', sa.String(length=255), nullable=False),
    sa.Column('RazonSocialCliente', sa.String(length=255), nullable=False),
    sa.Column('Ejecutivo', sa.String(length=255), nullable=False),
    sa.Column('FechaOperacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CodigoLiquidacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referidos')
    # ### end Alembic commands ###
