"""feat: agregar tabla actualizacion reportes

Revision ID: d4b6d8789b26
Revises: 0f1d8665602e
Create Date: 2025-04-14 18:59:59.647020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b6d8789b26'
down_revision: Union[str, None] = '0f1d8665602e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
