"""feat: añadir MontoNegociado

Revision ID: e9f39f240b8e
Revises: 9efafb6f4cc9
Create Date: 2024-10-15 14:52:27.998317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f39f240b8e'
down_revision: Union[str, None] = '9efafb6f4cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('MontoNegociado', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'MontoNegociado')
    # ### end Alembic commands ###
