"""feat: formato Lima/Peru v4- quitar

Revision ID: fb48631a8b4b
Revises: a40f4202cd50
Create Date: 2025-04-14 19:44:19.397921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb48631a8b4b'
down_revision: Union[str, None] = 'a40f4202cd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actualizacion_reportes', 'ultima_actualizacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualizacion_reportes', sa.Column('ultima_actualizacion', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
