"""add TipoCambio* and ColocacionSoles to kpi

Revision ID: fda7e53b939d
Revises: fed9402f4b19
Create Date: 2025-05-06 11:50:56.014054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fda7e53b939d'
down_revision: Union[str, None] = 'fed9402f4b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('TipoCambioFecha', sa.DateTime(), nullable=True))
    op.add_column('kpi', sa.Column('TipoCambioCompra', sa.Float(), nullable=True))
    op.add_column('kpi', sa.Column('TipoCambioVenta', sa.Float(), nullable=True))
    op.drop_column('kpi', 'tcFecha')
    op.drop_column('kpi', 'tcVenta')
    op.drop_column('kpi', 'tcCompra')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('tcCompra', mysql.FLOAT(), nullable=True))
    op.add_column('kpi', sa.Column('tcVenta', mysql.FLOAT(), nullable=True))
    op.add_column('kpi', sa.Column('tcFecha', mysql.DATETIME(), nullable=True))
    op.drop_column('kpi', 'TipoCambioVenta')
    op.drop_column('kpi', 'TipoCambioCompra')
    op.drop_column('kpi', 'TipoCambioFecha')
    # ### end Alembic commands ###
