"""feat: crear tabla referidos v1

Revision ID: feb54b67bfe0
Revises: 
Create Date: 2025-03-27 09:22:09.771909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'feb54b67bfe0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Referencia', sa.String(length=255), nullable=True),
    sa.Column('Moneda', sa.String(length=255), nullable=False),
    sa.Column('CodigoLiquidacion', sa.String(length=255), nullable=False),
    sa.Column('NroDocumento', sa.String(length=255), nullable=True),
    sa.Column('RazonSocialCliente', sa.String(length=255), nullable=False),
    sa.Column('Ejecutivo', sa.String(length=255), nullable=False),
    sa.Column('FechaOperacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CodigoLiquidacion')
    )
    op.drop_index('ix_Obligacionista_table_id', table_name='Obligacionista_table')
    op.drop_index('ix_Obligacionista_table_numero_documento', table_name='Obligacionista_table')
    op.drop_table('Obligacionista_table')
    op.alter_column('kpi', 'FechaConfirmado',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi', 'FechaConfirmado',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('Obligacionista_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombres', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('apellidos', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('domiciliado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('tipo_persona', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numero_documento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('genero', mysql.CHAR(length=1), nullable=True),
    sa.Column('domicilio_fiscal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('numero_telefono', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contrato_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cti', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('tasa', mysql.FLOAT(), nullable=True),
    sa.Column('moneda', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('plazo', sa.DATE(), nullable=True),
    sa.Column('tasa_castigo', mysql.FLOAT(), nullable=True),
    sa.Column('situacion_contrato', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contrato_fisico', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('codigo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notaria', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_firma_contrato', sa.DATE(), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('antecedentes', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('adenda_menor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('referido', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mancomunado_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capital_neto', mysql.FLOAT(), nullable=True),
    sa.Column('total_depositado', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_devuelto', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('capital', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('interes_bruto', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('capital_bruto', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('deposito_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capital_deposito', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha_transferencia', sa.DATE(), nullable=True),
    sa.Column('interes', mysql.FLOAT(), nullable=True),
    sa.Column('interes_mensual', mysql.FLOAT(), nullable=True),
    sa.Column('interes_factor', mysql.FLOAT(), nullable=True),
    sa.Column('dias_transcurridos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_corte_mensual', sa.DATE(), nullable=True),
    sa.Column('fecha_inicio_tramo', sa.DATE(), nullable=True),
    sa.Column('devolucion_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto_capital', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('monto_interes', mysql.FLOAT(), nullable=True),
    sa.Column('retencion', mysql.FLOAT(), nullable=True),
    sa.Column('interes_menos_retencion', mysql.FLOAT(), nullable=True),
    sa.Column('neto_a_pagar', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('motivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_de_entrega', mysql.DATETIME(), nullable=True),
    sa.Column('migrado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('monto_contrato', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('monto_deposito', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('codigo_obligacionista', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_auto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_auto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Obligacionista_table_numero_documento', 'Obligacionista_table', ['numero_documento'], unique=False)
    op.create_index('ix_Obligacionista_table_id', 'Obligacionista_table', ['id'], unique=False)
    op.drop_table('referidos')
    # ### end Alembic commands ###
