"""fix: created_by en el crm si puede ser null v2

Revision ID: 038e13296b6e
Revises: 628b8cb5447c
Create Date: 2025-06-05 08:52:25.018132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038e13296b6e'
down_revision: Union[str, None] = '628b8cb5447c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
