"""Initial creation of CRM database v2

Revision ID: 286a601fdf96
Revises: 518f65090426
Create Date: 2025-06-03 23:14:40.377745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286a601fdf96'
down_revision: Union[str, None] = '518f65090426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud_lead', sa.Column('estado', sa.Integer(), nullable=False))
    op.add_column('solicitud_lead', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.add_column('solicitud_lead', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('solicitud_lead', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('solicitud_lead', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud_lead', 'updated_at')
    op.drop_column('solicitud_lead', 'updated_by')
    op.drop_column('solicitud_lead', 'created_at')
    op.drop_column('solicitud_lead', 'created_by')
    op.drop_column('solicitud_lead', 'estado')
    # ### end Alembic commands ###
