"""Initial creation of CRM database

Revision ID: 518f65090426
Revises: 
Create Date: 2025-06-03 22:57:07.919658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518f65090426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_lead',
    sa.Column('solicitud_lead_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('ruc_cliente', sa.String(length=11), nullable=False),
    sa.Column('ruc_empresa', sa.String(length=11), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('acepta_terminos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('solicitud_lead_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_lead')
    # ### end Alembic commands ###
