"""fix: created_by en el crm si puede ser null

Revision ID: 628b8cb5447c
Revises: 286a601fdf96
Create Date: 2025-06-05 08:52:00.461827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '628b8cb5447c'
down_revision: Union[str, None] = '286a601fdf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitud_lead', 'created_by',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitud_lead', 'created_by',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
